---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: namespacedproviderconfigusages.kind.crossplane.io
spec:
  group: kind.crossplane.io
  names:
    categories:
    - crossplane
    - provider
    - kind
    kind: NamespacedProviderConfigUsage
    listKind: NamespacedProviderConfigUsageList
    plural: namespacedproviderconfigusages
    singular: namespacedproviderconfigusage
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    - jsonPath: .providerConfigRef.name
      name: CONFIG-NAME
      type: string
    - jsonPath: .resourceRef.kind
      name: RESOURCE-KIND
      type: string
    - jsonPath: .resourceRef.name
      name: RESOURCE-NAME
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: A NamespacedProviderConfigUsage indicates that a namespaced managed
          resource is using a ProviderConfig.
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation
              of an object.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this
              object represents.
            type: string
          metadata:
            type: object
          providerConfigRef:
            description: ProviderConfigReference to the ProviderConfig being used.
            properties:
              kind:
                description: Kind of the referenced ProviderConfig resource. Defaults
                  to ProviderConfig.
                type: string
              name:
                description: Name of the referenced ProviderConfig.
                type: string
            required:
            - name
            type: object
          resourceRef:
            description: ResourceReference to the namespaced managed resource using
              the ProviderConfig.
            properties:
              apiVersion:
                description: APIVersion of the referenced object.
                type: string
              kind:
                description: Kind of the referenced object.
                type: string
              name:
                description: Name of the referenced object.
                type: string
              namespace:
                description: Namespace of the referenced object.
                type: string
            required:
            - apiVersion
            - kind
            - name
            type: object
        required:
        - providerConfigRef
        - resourceRef
        type: object
    served: true
    storage: true
